//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace ProjectW10Client.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientsData", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ClientsData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BillNameField;
        
        private string ChargeAddressField;
        
        private int CountryIdField;
        
        private string CountryNameField;
        
        private System.Nullable<System.DateTime> CreationDateField;
        
        private string EmailField;
        
        private string FaxNumberField;
        
        private int IdField;
        
        private string IndustryIdField;
        
        private string IndustryNameField;
        
        private int LawyerIdField;
        
        private string LawyerNameField;
        
        private string NameField;
        
        private string PhoneNumberField;
        
        private string SendAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillName {
            get {
                return this.BillNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNameField, value) != true)) {
                    this.BillNameField = value;
                    this.RaisePropertyChanged("BillName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargeAddress {
            get {
                return this.ChargeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeAddressField, value) != true)) {
                    this.ChargeAddressField = value;
                    this.RaisePropertyChanged("ChargeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndustryId {
            get {
                return this.IndustryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryIdField, value) != true)) {
                    this.IndustryIdField = value;
                    this.RaisePropertyChanged("IndustryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndustryName {
            get {
                return this.IndustryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryNameField, value) != true)) {
                    this.IndustryNameField = value;
                    this.RaisePropertyChanged("IndustryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LawyerId {
            get {
                return this.LawyerIdField;
            }
            set {
                if ((this.LawyerIdField.Equals(value) != true)) {
                    this.LawyerIdField = value;
                    this.RaisePropertyChanged("LawyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LawyerName {
            get {
                return this.LawyerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LawyerNameField, value) != true)) {
                    this.LawyerNameField = value;
                    this.RaisePropertyChanged("LawyerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendAddress {
            get {
                return this.SendAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SendAddressField, value) != true)) {
                    this.SendAddressField = value;
                    this.RaisePropertyChanged("SendAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountriesData", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CountriesData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LawyersData", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LawyersData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> AddDateField;
        
        private int IdField;
        
        private string NameField;
        
        private string PositionField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ClientsInterface")]
    public interface ClientsInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientsInterface/GetClientsByLawyer", ReplyAction="http://tempuri.org/ClientsInterface/GetClientsByLawyerResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProjectW10Client.ServiceReference.ClientsData>> GetClientsByLawyerAsync(string Lawyer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientsInterface/GetCountries", ReplyAction="http://tempuri.org/ClientsInterface/GetCountriesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProjectW10Client.ServiceReference.CountriesData>> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientsInterface/GetLawyers", ReplyAction="http://tempuri.org/ClientsInterface/GetLawyersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProjectW10Client.ServiceReference.LawyersData>> GetLawyersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientsInterfaceChannel : ProjectW10Client.ServiceReference.ClientsInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientsInterfaceClient : System.ServiceModel.ClientBase<ProjectW10Client.ServiceReference.ClientsInterface>, ProjectW10Client.ServiceReference.ClientsInterface {
        
        public ClientsInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProjectW10Client.ServiceReference.ClientsData>> GetClientsByLawyerAsync(string Lawyer) {
            return base.Channel.GetClientsByLawyerAsync(Lawyer);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProjectW10Client.ServiceReference.CountriesData>> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProjectW10Client.ServiceReference.LawyersData>> GetLawyersAsync() {
            return base.Channel.GetLawyersAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
