//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Matters = new HashSet<Matter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BillName { get; set; }
        public string ChargeAddress { get; set; }
        public string SendAddress { get; set; }
        public int CountryId { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> LawyerId { get; set; }
        public string IndustryId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Lawyer Lawyer { get; set; }
        public virtual ICollection<Matter> Matters { get; set; }
    }
}
