//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawyer
    {
        public Lawyer()
        {
            this.Clients = new HashSet<Client>();
            this.Matters = new HashSet<Matter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Matter> Matters { get; set; }
    }
}
