//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matter
    {
        public int CompanyId { get; set; }
        public int MatterId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> LawyerId { get; set; }
        public string Name { get; set; }
        public Nullable<int> MatterTypeId { get; set; }
        public Nullable<decimal> ChargedFees { get; set; }
        public Nullable<decimal> ChargedExpenses { get; set; }
        public Nullable<decimal> DepositBalance { get; set; }
        public Nullable<decimal> FeesBalance { get; set; }
        public Nullable<decimal> PaidExpenses { get; set; }
        public Nullable<decimal> ExpensesBalance { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual Lawyer Lawyer { get; set; }
        public virtual MatterType MatterType { get; set; }
    }
}
